/**
 * Main orchestrator for Dart code generation.
 * Coordinates all sub-generators to produce the final output.
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import type {
  GeneratedFile,
  OverrideConfig,
  ResolvedSchema,
  EndpointInfo,
  ApiModuleInfo,
} from "../config/types.js";
import type { ParsedApi } from "../schema/openapi-parser.js";
import { collectInlineSchemas } from "../schema/openapi-parser.js";
import { isManualFile } from "../config/config-loader.js";
import { generateEntityFile } from "./entity-generator.js";
import { generateEnumFile } from "./enum-generator.js";
import { generateUnionTypeFile } from "./union-type-generator.js";
import { generateRequestFile } from "./request-generator.js";
import { generateResponseFile } from "./response-generator.js";
import { generateApiModuleFile } from "./api-module-generator.js";
import { generateMainClassFile } from "./main-class-generator.js";
import { generateExportFile } from "./export-generator.js";
import {
  classNameToFileName,
  pathToRequestClassName,
  pathToResponseClassName,
  pathToMethodName,
  pathPrefixToModuleClassName,
  pathToModuleFieldName,
  toCamelCase,
} from "../utils/naming.js";

/**
 * Generate all Dart files from the parsed API.
 */
export function generateAll(
  parsed: ParsedApi,
  config: OverrideConfig,
  outputDir: string
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. Generate entity classes from component schemas
  console.log("  Generating entities...");
  const entityFiles = generateEntities(parsed, config, outputDir);
  files.push(...entityFiles);

  // 2. Generate request/response types from endpoints
  console.log("  Generating request/response types...");
  const endpointFiles = generateEndpointTypes(parsed, config, outputDir);
  files.push(...endpointFiles);

  // 3. Generate API modules
  console.log("  Generating API modules...");
  const moduleFiles = generateApiModules(parsed, config, outputDir);
  files.push(...moduleFiles);

  // 4. Generate main Misskey class
  console.log("  Generating main class...");
  const mainFile = generateMainClass(parsed, config, outputDir);
  if (mainFile) files.push(mainFile);

  // Build set of class names defined in existing files (not generated by us)
  const existingClassNames = buildExistingClassNameSet(outputDir);

  // Write all files (skip existing files unless --overwrite is set)
  const overwrite = process.argv.includes("--overwrite");
  let written = 0;
  let skippedExisting = 0;
  let skippedConflict = 0;
  const writtenFiles: GeneratedFile[] = [];

  for (const file of files) {
    const fullPath = file.path;
    if (!overwrite && existsSync(fullPath)) {
      skippedExisting++;
      continue;
    }

    // Check if the file would define a class that conflicts with existing code
    const newClassNames = extractClassNamesFromContent(file.content);
    let hasConflict = false;
    for (const name of newClassNames) {
      if (existingClassNames.has(name)) {
        hasConflict = true;
        break;
      }
    }
    if (hasConflict) {
      skippedConflict++;
      continue;
    }

    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, file.content, "utf-8");
    writtenFiles.push(file);
    written++;
  }
  if (skippedExisting > 0) {
    console.log(`  Skipped ${skippedExisting} existing files (use --overwrite to replace)`);
  }
  if (skippedConflict > 0) {
    console.log(`  Skipped ${skippedConflict} files due to class name conflicts`);
  }

  // 5. Generate export file (always written - merges with existing)
  console.log("  Generating exports...");
  const exportFile = generateExports(files, config, outputDir);
  if (exportFile) {
    mkdirSync(dirname(exportFile.path), { recursive: true });
    writeFileSync(exportFile.path, exportFile.content, "utf-8");
    files.push(exportFile);
  }

  return files;
}

/**
 * Collect component schema names that are used as union (oneOf) variants.
 * These should not be generated as separate files since they become
 * factory constructors within the sealed class.
 */
function collectUnionVariantSchemas(parsed: ParsedApi): Set<string> {
  const variantNames = new Set<string>();
  for (const [, schema] of parsed.componentSchemas) {
    if (schema.type === "union" && schema.oneOf) {
      for (const variant of schema.oneOf) {
        if (variant.type === "ref" && variant.refTarget) {
          variantNames.add(variant.refTarget);
        }
      }
    }
  }
  return variantNames;
}

/**
 * Generate entity classes from component schemas.
 */
function generateEntities(
  parsed: ParsedApi,
  config: OverrideConfig,
  outputDir: string
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Collect schemas that are union variants (should be inlined in sealed class)
  const unionVariantSchemas = collectUnionVariantSchemas(parsed);

  for (const [name, schema] of parsed.componentSchemas) {
    const filePath = join(outputDir, "data", "base", `${classNameToFileName(name)}.dart`);

    // Skip manual files
    if (isManualFile(filePath, config)) continue;

    // Skip schemas that are used as union variants
    if (unionVariantSchemas.has(name)) continue;

    // Route to appropriate generator based on schema type
    const typeOverride = config.type_structure_overrides?.[name];

    let content: string | null = null;

    // Skip schemas with converter strategy (handled by manual converters)
    if (typeOverride?.strategy === "converter") continue;

    if (schema.type === "enum") {
      content = generateEnumFile(name, schema, config);
    } else if (schema.type === "union") {
      if (typeOverride?.strategy === "hierarchy") {
        content = generateEntityFile(name, schema, config, parsed);
      } else {
        content = generateUnionTypeFile(name, schema, config, parsed, typeOverride);
      }
    } else if (schema.allOf) {
      content = generateEntityFile(name, schema, config, parsed);
    } else if (schema.type === "object") {
      content = generateEntityFile(name, schema, config, parsed);
    }

    if (content) {
      files.push({ path: filePath, content });
    }
  }

  // Also generate inline schemas (objects and enums)
  const inlineSchemas = collectInlineSchemas(parsed);
  for (const [name, schema] of inlineSchemas) {
    const filePath = join(outputDir, "data", "base", `${classNameToFileName(name)}.dart`);
    if (isManualFile(filePath, config)) continue;

    let content: string | null = null;
    if (schema.type === "enum") {
      content = generateEnumFile(name, schema, config);
    } else {
      content = generateEntityFile(name, schema, config, parsed);
    }
    if (content) {
      files.push({ path: filePath, content });
    }
  }

  return files;
}

/**
 * Generate request and response types from endpoints.
 */
function generateEndpointTypes(
  parsed: ParsedApi,
  config: OverrideConfig,
  outputDir: string
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const endpoint of parsed.endpoints) {
    const pathSegments = endpoint.path.replace(/^\//, "").split("/");
    const subDir = pathSegments.length > 1 ? pathSegments[0] : "base";

    // Request type
    if (endpoint.hasRequestBody && endpoint.requestSchema) {
      const className = pathToRequestClassName(endpoint.path);
      const filePath = join(
        outputDir,
        "data",
        subDir,
        `${classNameToFileName(className)}.dart`
      );

      if (!isManualFile(filePath, config)) {
        const content = generateRequestFile(
          className,
          endpoint.requestSchema,
          config,
          parsed
        );
        if (content) files.push({ path: filePath, content });
      }
    }

    // Response type (only for inline response objects)
    if (
      endpoint.responseSchema &&
      endpoint.responseType === "single" &&
      endpoint.responseSchema.type === "object" &&
      endpoint.responseSchema.properties.size > 0 &&
      !endpoint.responseSchema.refTarget
    ) {
      const className = pathToResponseClassName(endpoint.path);
      const filePath = join(
        outputDir,
        "data",
        subDir,
        `${classNameToFileName(className)}.dart`
      );

      if (!isManualFile(filePath, config)) {
        const content = generateResponseFile(
          className,
          endpoint.responseSchema,
          config,
          parsed
        );
        if (content) files.push({ path: filePath, content });
      }
    }
  }

  return files;
}

/**
 * Build the API module tree from endpoints.
 */
export function buildModuleTree(
  endpoints: EndpointInfo[],
  config: OverrideConfig
): ApiModuleInfo[] {
  // Group endpoints by their first path segment
  const groups = new Map<string, EndpointInfo[]>();

  for (const ep of endpoints) {
    const segments = ep.path.replace(/^\//, "").split("/");
    const topLevel = segments[0];
    if (!groups.has(topLevel)) {
      groups.set(topLevel, []);
    }
    groups.get(topLevel)!.push(ep);
  }

  const modules: ApiModuleInfo[] = [];

  for (const [prefix, eps] of groups) {
    const module = buildModuleFromEndpoints(prefix, eps, config);
    modules.push(module);
  }

  return modules;
}

function buildModuleFromEndpoints(
  pathPrefix: string,
  endpoints: EndpointInfo[],
  config: OverrideConfig
): ApiModuleInfo {
  // Separate direct endpoints from sub-module endpoints
  const direct: EndpointInfo[] = [];
  const subGroups = new Map<string, EndpointInfo[]>();

  for (const ep of endpoints) {
    const relPath = ep.path
      .replace(/^\//, "")
      .slice(pathPrefix.length)
      .replace(/^\//, "");
    const segments = relPath.split("/").filter(Boolean);

    if (segments.length <= 1) {
      direct.push(ep);
    } else {
      const subPrefix = segments[0];
      const fullSubPrefix = `${pathPrefix}/${subPrefix}`;
      if (!subGroups.has(fullSubPrefix)) {
        subGroups.set(fullSubPrefix, []);
      }
      subGroups.get(fullSubPrefix)!.push(ep);
    }
  }

  const subModules: ApiModuleInfo[] = [];
  for (const [subPrefix, subEps] of subGroups) {
    subModules.push(buildModuleFromEndpoints(subPrefix, subEps, config));
  }

  return {
    name: pathPrefixToModuleClassName(pathPrefix),
    dartName: pathPrefixToModuleClassName(pathPrefix),
    fieldName: pathToModuleFieldName(pathPrefix),
    pathPrefix,
    endpoints: direct,
    subModules,
  };
}

/**
 * Generate API module files.
 */
function generateApiModules(
  parsed: ParsedApi,
  config: OverrideConfig,
  outputDir: string
): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const modules = buildModuleTree(parsed.endpoints, config);

  for (const mod of modules) {
    const filePath = join(
      outputDir,
      `misskey_${classNameToFileName(mod.fieldName)}.dart`
    );
    if (isManualFile(filePath, config)) continue;

    const content = generateApiModuleFile(mod, config, parsed);
    if (content) files.push({ path: filePath, content });
  }

  return files;
}

/**
 * Generate main Misskey class.
 */
function generateMainClass(
  parsed: ParsedApi,
  config: OverrideConfig,
  outputDir: string
): GeneratedFile | null {
  const filePath = join(outputDir, "misskey_dart_base.dart");
  if (isManualFile(filePath, config)) return null;

  const modules = buildModuleTree(parsed.endpoints, config);
  const content = generateMainClassFile(modules, config, parsed);
  if (!content) return null;

  return { path: filePath, content };
}

/**
 * Generate export file.
 */
function generateExports(
  generatedFiles: GeneratedFile[],
  config: OverrideConfig,
  outputDir: string
): GeneratedFile | null {
  const exportPath = resolve(outputDir, "..", "misskey_dart.dart");
  const content = generateExportFile(generatedFiles, config, outputDir);
  if (!content) return null;
  return { path: exportPath, content };
}

/**
 * Extract class/enum/mixin names from Dart source content.
 */
function extractClassNamesFromContent(content: string): Set<string> {
  const names = new Set<string>();
  const pattern = /^\s*(?:abstract\s+)?(?:sealed\s+)?(?:class|enum|mixin)\s+(\w+)/gm;
  let match;
  while ((match = pattern.exec(content)) !== null) {
    names.add(match[1]);
  }
  return names;
}

/**
 * Build a set of all class/enum names defined in existing Dart files.
 * Scans all .dart files in the output directory (recursively).
 */
function buildExistingClassNameSet(outputDir: string): Set<string> {
  const names = new Set<string>();
  const libDir = dirname(outputDir);

  function scanDir(dir: string) {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const fullPath = join(dir, entry);
      try {
        const stat = statSync(fullPath);
        if (stat.isDirectory()) {
          scanDir(fullPath);
        } else if (entry.endsWith(".dart") && !entry.endsWith(".freezed.dart") && !entry.endsWith(".g.dart")) {
          const content = readFileSync(fullPath, "utf-8");
          for (const name of extractClassNamesFromContent(content)) {
            names.add(name);
          }
        }
      } catch {
        // Skip unreadable files
      }
    }
  }

  scanDir(libDir);
  return names;
}
